# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(805, 548)
        Form.setMinimumSize(QtCore.QSize(805, 548))
        Form.setMaximumSize(QtCore.QSize(805, 548))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setStyleSheet("QWidget{\n"
"background-color:#060621;\n"
"\n"
"}")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(770, 10, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"color:#500004;\n"
"background:#ff5c5a;\n"
"border-radius:10;\n"
"}")
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(0, -10, 201, 561))
        self.groupBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"background-color:rgb(5,19,54);\n"
"box-shadow: 5px 10px #000000;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.sys_info_btn = QtWidgets.QPushButton(self.groupBox)
        self.sys_info_btn.setGeometry(QtCore.QRect(0, 180, 201, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.sys_info_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sys_info_btn.setFont(font)
        self.sys_info_btn.setStyleSheet("\n"
"QPushButton {\n"
"    color:white;\n"
"    background:black;\n"
"    transition: all 0.3s ease 0s;\n"
"    cursor: pointer;\n"
"    outline: none;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2EE59D;\n"
"    box-shadow: 0px 15px 20px rgba(46, 229, 157, 0.4);\n"
"    color: #fff;\n"
"    transform: translateY(-7px);\n"
"    }")
        self.sys_info_btn.setFlat(False)
        self.sys_info_btn.setObjectName("sys_info_btn")
        self.cpu_info_btn = QtWidgets.QPushButton(self.groupBox)
        self.cpu_info_btn.setGeometry(QtCore.QRect(0, 240, 201, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.cpu_info_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cpu_info_btn.setFont(font)
        self.cpu_info_btn.setStyleSheet("\n"
"QPushButton {\n"
"    color:white;\n"
"    background:black;\n"
"    transition: all 0.3s ease 0s;\n"
"    cursor: pointer;\n"
"    outline: none;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2EE59D;\n"
"    box-shadow: 0px 15px 20px rgba(46, 229, 157, 0.4);\n"
"    color: #fff;\n"
"    transform: translateY(-7px);\n"
"    }")
        self.cpu_info_btn.setFlat(False)
        self.cpu_info_btn.setObjectName("cpu_info_btn")
        self.mem_info_btn = QtWidgets.QPushButton(self.groupBox)
        self.mem_info_btn.setGeometry(QtCore.QRect(0, 300, 201, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.mem_info_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mem_info_btn.setFont(font)
        self.mem_info_btn.setStyleSheet("\n"
"QPushButton {\n"
"    color:white;\n"
"    background:black;\n"
"    transition: all 0.3s ease 0s;\n"
"    cursor: pointer;\n"
"    outline: none;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2EE59D;\n"
"    box-shadow: 0px 15px 20px rgba(46, 229, 157, 0.4);\n"
"    color: #fff;\n"
"    transform: translateY(-7px);\n"
"    }")
        self.mem_info_btn.setFlat(False)
        self.mem_info_btn.setObjectName("mem_info_btn")
        self.serials_btn = QtWidgets.QPushButton(self.groupBox)
        self.serials_btn.setGeometry(QtCore.QRect(0, 360, 201, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.serials_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.serials_btn.setFont(font)
        self.serials_btn.setStyleSheet("\n"
"QPushButton {\n"
"    color:white;\n"
"    background:black;\n"
"    transition: all 0.3s ease 0s;\n"
"    cursor: pointer;\n"
"    outline: none;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2EE59D;\n"
"    box-shadow: 0px 15px 20px rgba(46, 229, 157, 0.4);\n"
"    color: #fff;\n"
"    transform: translateY(-7px);\n"
"    }")
        self.serials_btn.setFlat(False)
        self.serials_btn.setObjectName("serials_btn")
        self.network_info_btn = QtWidgets.QPushButton(self.groupBox)
        self.network_info_btn.setGeometry(QtCore.QRect(0, 420, 201, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.network_info_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.network_info_btn.setFont(font)
        self.network_info_btn.setStyleSheet("\n"
"QPushButton {\n"
"    color:white;\n"
"    background:black;\n"
"    transition: all 0.3s ease 0s;\n"
"    cursor: pointer;\n"
"    outline: none;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2EE59D;\n"
"    box-shadow: 0px 15px 20px rgba(46, 229, 157, 0.4);\n"
"    color: #fff;\n"
"    transform: translateY(-7px);\n"
"    }")
        self.network_info_btn.setFlat(False)
        self.network_info_btn.setObjectName("network_info_btn")
        self.smpl_Info_btn = QtWidgets.QPushButton(self.groupBox)
        self.smpl_Info_btn.setGeometry(QtCore.QRect(0, 120, 201, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.smpl_Info_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.smpl_Info_btn.setFont(font)
        self.smpl_Info_btn.setStyleSheet("\n"
"QPushButton {\n"
"    color:white;\n"
"    background:black;\n"
"    transition: all 0.3s ease 0s;\n"
"    cursor: pointer;\n"
"    outline: none;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2EE59D;\n"
"    box-shadow: 0px 15px 20px rgba(46, 229, 157, 0.4);\n"
"    color: #fff;\n"
"    transform: translateY(-7px);\n"
"    }")
        self.smpl_Info_btn.setFlat(False)
        self.smpl_Info_btn.setObjectName("smpl_Info_btn")
        self.header = QtWidgets.QLabel(self.groupBox)
        self.header.setEnabled(True)
        self.header.setGeometry(QtCore.QRect(20, 30, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.header.setFont(font)
        self.header.setStyleSheet("QLabel{\n"
"color:white;\n"
"background-color:#051336;\n"
"font-size:12pt;\n"
"}")
        self.header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header.setFrameShadow(QtWidgets.QFrame.Plain)
        self.header.setTextFormat(QtCore.Qt.PlainText)
        self.header.setObjectName("header")
        self.version = QtWidgets.QLabel(self.groupBox)
        self.version.setEnabled(True)
        self.version.setGeometry(QtCore.QRect(20, 480, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.version.setFont(font)
        self.version.setStyleSheet("QLabel{\n"
"color:white;\n"
"background-color:#051336;\n"
"font-size:12pt;\n"
"}")
        self.version.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.version.setFrameShadow(QtWidgets.QFrame.Plain)
        self.version.setTextFormat(QtCore.Qt.PlainText)
        self.version.setObjectName("version")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(100, -10, 111, 571))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"background-color:#040418;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(230, 50, 551, 491))
        self.stackedWidget.setLineWidth(-1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.logo = QtWidgets.QLabel(self.home)
        self.logo.setGeometry(QtCore.QRect(110, 80, 341, 321))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setOpenExternalLinks(True)
        self.logo.setObjectName("logo")
        self.stackedWidget.addWidget(self.home)
        self.simple_page = QtWidgets.QWidget()
        self.simple_page.setObjectName("simple_page")
        self.btry_lbl = QtWidgets.QLabel(self.simple_page)
        self.btry_lbl.setGeometry(QtCore.QRect(100, 160, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btry_lbl.setFont(font)
        self.btry_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.btry_lbl.setObjectName("btry_lbl")    
        self.btry_prog_bar = QtWidgets.QProgressBar(self.simple_page)
        self.btry_prog_bar.setGeometry(QtCore.QRect(250, 170, 161, 23))
        self.btry_prog_bar.setStyleSheet("QProgressBar{\n"
"color:white;\n"
"}")
        self.btry_prog_bar.setProperty("value", 24)
        self.btry_prog_bar.setObjectName("btry_prog_bar")
        self.plug_lbl = QtWidgets.QLabel(self.simple_page)
        self.plug_lbl.setGeometry(QtCore.QRect(100, 210,400, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plug_lbl.setFont(font)
        self.plug_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.plug_lbl.setObjectName("plug_lbl")
#         self.time_left_lbl = QtWidgets.QLabel(self.simple_page)
#         self.time_left_lbl.setGeometry(QtCore.QRect(100, 240,400, 41))
#         font = QtGui.QFont()
#         font.setPointSize(13)
#         self.time_left_lbl.setFont(font)
#         self.time_left_lbl.setStyleSheet("QLabel{\n"
# "color:white;\n"
# "}\n"
# "")
#         self.time_left_lbl.setObjectName("time_left_lbl")
        self.boot_lbl = QtWidgets.QLabel(self.simple_page)
        self.boot_lbl.setGeometry(QtCore.QRect(100, 250, 400, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.boot_lbl.setFont(font)
        self.boot_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.boot_lbl.setObjectName("boot_lbl")
        self.stackedWidget.addWidget(self.simple_page)
        self.system_page = QtWidgets.QWidget()
        self.system_page.setObjectName("system_page")
        self.proces_lbl = QtWidgets.QLabel(self.system_page)
        self.proces_lbl.setGeometry(QtCore.QRect(90, 310, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.proces_lbl.setFont(font)
        self.proces_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.proces_lbl.setObjectName("proces_lbl")
        self.node_lbl = QtWidgets.QLabel(self.system_page)
        self.node_lbl.setGeometry(QtCore.QRect(90, 150, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.node_lbl.setFont(font)
        self.node_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.node_lbl.setObjectName("node_lbl")
        self.reles_lbl = QtWidgets.QLabel(self.system_page)
        self.reles_lbl.setGeometry(QtCore.QRect(90, 190, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.reles_lbl.setFont(font)
        self.reles_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.reles_lbl.setObjectName("reles_lbl")
        self.vrsion_lbl = QtWidgets.QLabel(self.system_page)
        self.vrsion_lbl.setGeometry(QtCore.QRect(90, 230, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.vrsion_lbl.setFont(font)
        self.vrsion_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.vrsion_lbl.setObjectName("vrsion_lbl")
        self.sys_lbl = QtWidgets.QLabel(self.system_page)
        self.sys_lbl.setGeometry(QtCore.QRect(90, 110, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sys_lbl.setFont(font)
        self.sys_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.sys_lbl.setObjectName("sys_lbl")
        self.mchin_lbl = QtWidgets.QLabel(self.system_page)
        self.mchin_lbl.setGeometry(QtCore.QRect(90, 270, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mchin_lbl.setFont(font)
        self.mchin_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.mchin_lbl.setObjectName("mchin_lbl")
        self.stackedWidget.addWidget(self.system_page)
        self.cpu_page = QtWidgets.QWidget()
        self.cpu_page.setObjectName("cpu_page")
        self.tot_cpu_use_lbl = QtWidgets.QLabel(self.cpu_page)
        self.tot_cpu_use_lbl.setGeometry(QtCore.QRect(90, 310, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tot_cpu_use_lbl.setFont(font)
        self.tot_cpu_use_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.tot_cpu_use_lbl.setObjectName("tot_cpu_use_lbl")
        self.phys_core_lbl = QtWidgets.QLabel(self.cpu_page)
        self.phys_core_lbl.setGeometry(QtCore.QRect(90, 110, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.phys_core_lbl.setFont(font)
        self.phys_core_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.phys_core_lbl.setObjectName("phys_core_lbl")
        self.crnt_freq_lbl = QtWidgets.QLabel(self.cpu_page)
        self.crnt_freq_lbl.setGeometry(QtCore.QRect(90, 270, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.crnt_freq_lbl.setFont(font)
        self.crnt_freq_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.crnt_freq_lbl.setObjectName("crnt_freq_lbl")
        self.min_freq_lbl = QtWidgets.QLabel(self.cpu_page)
        self.min_freq_lbl.setGeometry(QtCore.QRect(90, 230, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.min_freq_lbl.setFont(font)
        self.min_freq_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.min_freq_lbl.setObjectName("min_freq_lbl")
        self.tot_core_lbl = QtWidgets.QLabel(self.cpu_page)
        self.tot_core_lbl.setGeometry(QtCore.QRect(90, 150, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tot_core_lbl.setFont(font)
        self.tot_core_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.tot_core_lbl.setObjectName("tot_core_lbl")
        self.max_freq_lbl = QtWidgets.QLabel(self.cpu_page)
        self.max_freq_lbl.setGeometry(QtCore.QRect(90, 190, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.max_freq_lbl.setFont(font)
        self.max_freq_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.max_freq_lbl.setObjectName("max_freq_lbl")
        self.tot_cpu_bar = QtWidgets.QProgressBar(self.cpu_page)
        self.tot_cpu_bar.setGeometry(QtCore.QRect(280, 320, 118, 23))
        self.tot_cpu_bar.setStyleSheet("QProgressBar{\n"
"color:white;\n"
"}")
        self.tot_cpu_bar.setProperty("value", 24)
        self.tot_cpu_bar.setObjectName("tot_cpu_bar")
        self.stackedWidget.addWidget(self.cpu_page)
        self.memory_page = QtWidgets.QWidget()
        self.memory_page.setObjectName("memory_page")
        self.mem_prog_bar = QtWidgets.QProgressBar(self.memory_page)
        self.mem_prog_bar.setGeometry(QtCore.QRect(310, 200, 151, 23))
        self.mem_prog_bar.setStyleSheet("QProgressBar{\n"
"color:white;\n"
"}")
        self.mem_prog_bar.setProperty("value", 24)
        self.mem_prog_bar.setObjectName("mem_prog_bar")
        self.avlb_mem_lbl = QtWidgets.QLabel(self.memory_page)
        self.avlb_mem_lbl.setGeometry(QtCore.QRect(90, 110, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.avlb_mem_lbl.setFont(font)
        self.avlb_mem_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.avlb_mem_lbl.setObjectName("avlb_mem_lbl")
        self.used_mem_lbl = QtWidgets.QLabel(self.memory_page)
        self.used_mem_lbl.setGeometry(QtCore.QRect(90, 150, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.used_mem_lbl.setFont(font)
        self.used_mem_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.used_mem_lbl.setObjectName("used_mem_lbl")
        self.tot_swap_lbl = QtWidgets.QLabel(self.memory_page)
        self.tot_swap_lbl.setGeometry(QtCore.QRect(90, 230, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tot_swap_lbl.setFont(font)
        self.tot_swap_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.tot_swap_lbl.setObjectName("tot_swap_lbl")
        self.perc_mem_lbl = QtWidgets.QLabel(self.memory_page)
        self.perc_mem_lbl.setGeometry(QtCore.QRect(90, 190, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.perc_mem_lbl.setFont(font)
        self.perc_mem_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.perc_mem_lbl.setObjectName("perc_mem_lbl")
        self.used_swap_lbl = QtWidgets.QLabel(self.memory_page)
        self.used_swap_lbl.setGeometry(QtCore.QRect(90, 310, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.used_swap_lbl.setFont(font)
        self.used_swap_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.used_swap_lbl.setObjectName("used_swap_lbl")
        self.tot_mem_lbl = QtWidgets.QLabel(self.memory_page)
        self.tot_mem_lbl.setGeometry(QtCore.QRect(90, 70, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tot_mem_lbl.setFont(font)
        self.tot_mem_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.tot_mem_lbl.setObjectName("tot_mem_lbl")
        self.perc_swap_lbl = QtWidgets.QLabel(self.memory_page)
        self.perc_swap_lbl.setGeometry(QtCore.QRect(90, 350, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.perc_swap_lbl.setFont(font)
        self.perc_swap_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.perc_swap_lbl.setObjectName("perc_swap_lbl")
        self.free_swap_lbl = QtWidgets.QLabel(self.memory_page)
        self.free_swap_lbl.setGeometry(QtCore.QRect(90, 270, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.free_swap_lbl.setFont(font)
        self.free_swap_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.free_swap_lbl.setObjectName("free_swap_lbl")
        self.swap_prog_bar = QtWidgets.QProgressBar(self.memory_page)
        self.swap_prog_bar.setGeometry(QtCore.QRect(290, 360, 118, 23))
        self.swap_prog_bar.setStyleSheet("QProgressBar{\n"
"color:white;\n"
"}")
        self.swap_prog_bar.setProperty("value", 24)
        self.swap_prog_bar.setObjectName("swap_prog_bar")
        self.stackedWidget.addWidget(self.memory_page)
        self.serials_page = QtWidgets.QWidget()
        self.serials_page.setObjectName("serials_page")
        self.board_serial_lbl = QtWidgets.QLabel(self.serials_page)
        self.board_serial_lbl.setGeometry(QtCore.QRect(90, 160, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.board_serial_lbl.setFont(font)
        self.board_serial_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.board_serial_lbl.setObjectName("board_serial_lbl")
        self.cpu_serial_lbl = QtWidgets.QLabel(self.serials_page)
        self.cpu_serial_lbl.setGeometry(QtCore.QRect(90, 200, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cpu_serial_lbl.setFont(font)
        self.cpu_serial_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.cpu_serial_lbl.setObjectName("cpu_serial_lbl")

        self.ram_serial_lbl = QtWidgets.QLabel(self.serials_page)
        self.ram_serial_lbl.setGeometry(QtCore.QRect(90, 240, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ram_serial_lbl.setFont(font)
        self.ram_serial_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.ram_serial_lbl.setObjectName("ram_serial_lbl")
        self.disk_serial_lbl = QtWidgets.QLabel(self.serials_page)
        self.disk_serial_lbl.setGeometry(QtCore.QRect(90, 280, 400, 82))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.disk_serial_lbl.setFont(font)
        self.disk_serial_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.disk_serial_lbl.setObjectName("disk_serial_lbl")

        self.bios_serial_lbl = QtWidgets.QLabel(self.serials_page)
        self.bios_serial_lbl.setGeometry(QtCore.QRect(90, 360, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.bios_serial_lbl.setFont(font)
        self.bios_serial_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.bios_serial_lbl.setObjectName("bios_serial_lbl")

        # self.disk_table = QtWidgets.QTableWidget(self.serials_page)
        # self.disk_table.setGeometry(QtCore.QRect(25, 41, 511, 411))
        # self.disk_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        # self.disk_table.setObjectName("disk_table")
        # self.disk_table.setColumnCount(7)
        # self.disk_table.setRowCount(0)
        # item = QtWidgets.QTableWidgetItem()
        # self.disk_table.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.disk_table.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.disk_table.setHorizontalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.disk_table.setHorizontalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.disk_table.setHorizontalHeaderItem(4, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.disk_table.setHorizontalHeaderItem(5, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.disk_table.setHorizontalHeaderItem(6, item)
        self.stackedWidget.addWidget(self.serials_page)
        self.network_page = QtWidgets.QWidget()
        self.network_page.setObjectName("network_page")
#         self.tableWidget_3 = QtWidgets.QTableWidget(self.network_page)
#         self.tableWidget_3.setGeometry(QtCore.QRect(25, 41, 501, 311))
#         self.tableWidget_3.setStyleSheet("QTableWidget{\n"
# "color:white;\n"
# "}")
#         self.tableWidget_3.setFrameShape(QtWidgets.QFrame.NoFrame)
#         self.tableWidget_3.setFrameShadow(QtWidgets.QFrame.Plain)
#         self.tableWidget_3.setLineWidth(0)
#         self.tableWidget_3.setShowGrid(False)
#         self.tableWidget_3.setObjectName("tableWidget_3")
#         self.tableWidget_3.setColumnCount(4)
#         self.tableWidget_3.setRowCount(0)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget_3.setHorizontalHeaderItem(0, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget_3.setHorizontalHeaderItem(1, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget_3.setHorizontalHeaderItem(2, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.byt_sent_lbl = QtWidgets.QLabel(self.network_page)
        self.byt_sent_lbl.setGeometry(QtCore.QRect(50, 200, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.byt_sent_lbl.setFont(font)
        self.byt_sent_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.byt_sent_lbl.setObjectName("byt_sent_lbl")
        self.byt_recev_lbl = QtWidgets.QLabel(self.network_page)
        self.byt_recev_lbl.setGeometry(QtCore.QRect(50, 240, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.byt_recev_lbl.setFont(font)
        self.byt_recev_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.byt_recev_lbl.setObjectName("byt_recev_lbl")
        self.mac_lbl = QtWidgets.QLabel(self.network_page)
        self.mac_lbl.setGeometry(QtCore.QRect(50, 280, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mac_lbl.setFont(font)
        self.mac_lbl.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"")
        self.mac_lbl.setObjectName("mac_lbl")

        self.stackedWidget.addWidget(self.network_page)
        self.groupBox_2.raise_()
        self.pushButton.raise_()
        self.groupBox.raise_()
        self.stackedWidget.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PC Performance Monitoring"))
        self.pushButton.setText(_translate("Form", "x"))
        self.sys_info_btn.setText(_translate("Form", "system Information"))
        self.cpu_info_btn.setText(_translate("Form", "CPU Information"))
        self.mem_info_btn.setText(_translate("Form", "Memory Information"))
        self.serials_btn.setText(_translate("Form", "Serial Numbers"))
        self.network_info_btn.setText(_translate("Form", "Network Information"))
        self.smpl_Info_btn.setText(_translate("Form", "simple Information"))
        self.header.setText(_translate("Form", "PC Performance\n"
"MONOTORING"))
        self.version.setText(_translate("Form", "BY:Mohamed Emad \n"
"& Abdo Mohamed"))
        self.btry_prog_bar.setFormat(_translate("Form", "%p%"))
        self.btry_lbl.setText(_translate("Form", "battery level :"))
        self.plug_lbl.setText(_translate("Form", "Plugged :"))
        #self.time_left_lbl.setText(_translate("Form", "Time left :"))
        self.boot_lbl.setText(_translate("Form", "Boot Time :"))
        self.proces_lbl.setText(_translate("Form", "Processor :"))
        self.node_lbl.setText(_translate("Form", "Node Name :"))
        self.reles_lbl.setText(_translate("Form", "Release :"))
        self.vrsion_lbl.setText(_translate("Form", "Version :"))
        self.sys_lbl.setText(_translate("Form", "System :"))
        self.mchin_lbl.setText(_translate("Form", "Machine :"))
        self.tot_cpu_use_lbl.setText(_translate("Form", "Total CPU usage :"))
        self.phys_core_lbl.setText(_translate("Form", "Physical cores :"))
        self.crnt_freq_lbl.setText(_translate("Form", "Currnet Frequency :"))
        self.min_freq_lbl.setText(_translate("Form", "Minimum Frequency :"))
        self.tot_core_lbl.setText(_translate("Form", "Total cores :"))
        self.max_freq_lbl.setText(_translate("Form", "Maximum Frequency :"))
        self.mem_prog_bar.setFormat(_translate("Form", "%p%"))
        self.avlb_mem_lbl.setText(_translate("Form", "Available Memory"))
        self.used_mem_lbl.setText(_translate("Form", "Used Memory"))
        self.tot_swap_lbl.setText(_translate("Form", "Total Swap"))
        self.perc_mem_lbl.setText(_translate("Form", "Memory Percentage :"))
        self.used_swap_lbl.setText(_translate("Form", "Used Swap"))
        self.tot_mem_lbl.setText(_translate("Form", "Total Memory"))
        self.perc_swap_lbl.setText(_translate("Form", "Swap Percentage :"))
        self.free_swap_lbl.setText(_translate("Form", "Free Swap"))
        self.ram_serial_lbl.setText(_translate("Form", "RAM serial"))
        self.disk_serial_lbl.setText(_translate("Form", "Disk serial"))
        self.cpu_serial_lbl.setText(_translate("Form", "CPU serial"))
        self.board_serial_lbl.setText(_translate("Form", "board serial"))
        self.bios_serial_lbl.setText(_translate("Form", "BIOS serial"))
        # item = self.disk_table.horizontalHeaderItem(0)
        # item.setText(_translate("Form", "Device"))
        # item = self.disk_table.horizontalHeaderItem(1)
        # item.setText(_translate("Form", "MountPoint"))
        # item = self.disk_table.horizontalHeaderItem(2)
        # item.setText(_translate("Form", "file system type"))
        # item = self.disk_table.horizontalHeaderItem(3)
        # item.setText(_translate("Form", "total size"))
        # item = self.disk_table.horizontalHeaderItem(4)
        # item.setText(_translate("Form", "used size"))
        # item = self.disk_table.horizontalHeaderItem(5)
        # item.setText(_translate("Form", "free size"))
        # item = self.disk_table.horizontalHeaderItem(6)
        # item.setText(_translate("Form", "percentage"))
        # item = self.tableWidget_3.horizontalHeaderItem(0)
        # item.setText(_translate("Form", "interface"))
        # item = self.tableWidget_3.horizontalHeaderItem(1)
        # item.setText(_translate("Form", "ip address"))
        # item = self.tableWidget_3.horizontalHeaderItem(2)
        # item.setText(_translate("Form", "net mask"))
        # item = self.tableWidget_3.horizontalHeaderItem(3)
        # item.setText(_translate("Form", "broadcast ip"))
        self.mac_lbl.setText(_translate("Form", "Your MAC address : "))
        self.byt_sent_lbl.setText(_translate("Form", "total bytes sent : "))
        self.byt_recev_lbl.setText(_translate("Form", "total bytes received : "))
